# Description: Launchpad is a library that simplifies writing distributed
# programs and seamlessly launching them on a range of supported platforms.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files(["LICENSE"])
